Repository ArtemPrivet/FocusStartHomeworks, pull requests merged in 2019-11, with the labels that each got.

#18 Добавление домашнего задания 2
  .gitignore
  .travis.yml
  Homework2/.swiftlint.yml
  Homework2/Homework2.xcodeproj/project.pbxproj
  Homework2/Homework2.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Homework2/Homework2.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Homework2/Homework2.xcodeproj/xcshareddata/xcschemes/Homework2.xcscheme
  Homework2/Homework2/AppDelegate.swift
  Homework2/Homework2/String+Extensions.swift
  Homework2/Homework2/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  Homework2/Homework2/SupportingFiles/Assets.xcassets/Contents.json
  Homework2/Homework2/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  Homework2/Homework2/SupportingFiles/Info.plist
  Homework2/Homework2Tests/CalculatorTests.swift
  Homework2/Homework2Tests/Info.plist
  README.md
  install_swiftlint.sh
Labels: homework

#47 Добавил домашнее задание 3
  .travis.yml
  Homework3/.swiftlint.yml
  Homework3/Homework3.xcodeproj/project.pbxproj
  Homework3/Homework3.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Homework3/Homework3.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Homework3/Homework3.xcodeproj/xcshareddata/xcschemes/Homework3.xcscheme
  Homework3/Homework3/AppDelegate.swift
  Homework3/Homework3/Sequence+Extensions.swift
  Homework3/Homework3/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  Homework3/Homework3/SupportingFiles/Assets.xcassets/Contents.json
  Homework3/Homework3/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  Homework3/Homework3/SupportingFiles/Info.plist
  Homework3/Homework3Tests/CalculatorTests.swift
  Homework3/Homework3Tests/Info.plist
  README.md
Labels: homework, 🌟 Needs more Approvals, 🔍 Ready for Review

#62 Добавил ДЗ с Calculator
  .travis.yml
  Calculator/.swiftlint.yml
  Calculator/Calculator.xcodeproj/project.pbxproj
  Calculator/Calculator.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Calculator/Calculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Calculator/Calculator/Application/AppDelegate.swift
  Calculator/Calculator/Controllers/CalculatorViewController.swift
  Calculator/Calculator/Resources/Fonts/FiraSans-Light.ttf
  Calculator/Calculator/Resources/Fonts/FiraSans-Regular.ttf
  Calculator/Calculator/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  Calculator/Calculator/SupportingFiles/Assets.xcassets/Contents.json
  Calculator/Calculator/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  Calculator/Calculator/SupportingFiles/Info.plist
  Calculator/CalculatorTests/CalculatorTests.swift
  Calculator/CalculatorTests/Info.plist
  README.md
Labels: 🌟 Needs more Approvals, 🔍 Ready for Review

#72 TEST: Исправил версию swiftlint в скрипте
  install_swiftlint.sh
Labels: 🔍 Ready for Review

#74 CI: Обновил версию симулятора
  .travis.yml
Labels: 🔍 Ready for Review
